# Generated by Django 4.2.5 on 2023-10-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_producto_delete_prod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(default='b27f7bb7c1d0424790ce13fe7fd6ac06', max_length=50, unique=True),
        ),
    ]
