# Generated by Django 4.2.5 on 2023-10-04 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_delete_curso_delete_profesor_producto_codigo_barras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(default='e3e8985d20074335b1d8d3a0387914c8', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='StockDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.deposito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.producto')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.deposito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.producto')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.tipomovimiento')),
            ],
        ),
        migrations.AddField(
            model_name='deposito',
            name='productos',
            field=models.ManyToManyField(through='AppCoder.StockDeposito', to='AppCoder.producto'),
        ),
    ]
