# Generated by Django 4.2.5 on 2023-10-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_deposito_tipomovimiento_alter_producto_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(default='1b00b56afe5347239d1f243cc2a7f8c0', max_length=50, unique=True),
        ),
    ]
