# Generated by Django 4.2.5 on 2023-10-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_alter_producto_codigo_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(default='bbda371180004a08ad72d224e1387634', max_length=50),
        ),
    ]
