# Generated by Django 4.2.5 on 2023-10-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_alter_producto_codigo_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposito',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(default='7fb1d329580e47e18057cbebf9bf9bc4', max_length=50),
        ),
    ]
