# Generated by Django 4.2.5 on 2023-10-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_alter_producto_codigo_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(default='5ebb44d213324f59b0df5b47b0878e92', max_length=50),
        ),
    ]
