# Generated by Django 4.2.5 on 2023-10-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0011_alter_producto_codigo_barras_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(default='ed345bea79eb4bc697d291e1088bfc4f', max_length=50),
        ),
    ]
