# Generated by Django 4.2.5 on 2023-10-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0012_alter_producto_codigo_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(default='75c3d524b8bc4b09bf4209f5b009f55d', max_length=50),
        ),
    ]
