# Generated by Django 4.2.5 on 2023-10-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0013_alter_producto_codigo_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(default='833b082264974e619c8a4486dbe2115e', max_length=50),
        ),
    ]
