# Generated by Django 4.2.5 on 2023-10-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0014_alter_producto_codigo_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(default='f25be07e66584853994f89dfaf5a6508', max_length=50),
        ),
    ]
