# Generated by Django 4.2.5 on 2023-10-09 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0017_customuser_user_profile_alter_producto_codigo_barras_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_profile',
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(default='ff22640b309b4ef686edb797106ef8b0', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='AppCoder.customuser'),
        ),
    ]
