# Generated by Django 4.2.5 on 2023-10-09 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0018_remove_customuser_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='AppCoder.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(default='13e21ed72173483493a6648b623f948b', max_length=50),
        ),
    ]
