# Generated by Django 4.2.5 on 2023-10-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0019_customuser_user_profile_alter_producto_codigo_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(default='2e07ccc0de984c3b9000d652584f1f86', max_length=50),
        ),
    ]
