# Generated by Django 4.2.5 on 2023-10-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0020_alter_producto_codigo_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(default='9af41faa0409462db2d4513e04a96320', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='media/default_avatar.png', upload_to='media/'),
        ),
    ]
