# Generated by Django 4.2.5 on 2023-10-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0024_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(default='406f2b2ca9b84fa09b91e3cf2fd7dfb9', max_length=50),
        ),
    ]
