# Generated by Django 4.2.5 on 2023-10-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0028_userprofile_bio_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(default='c1a7535b11b24482882a6902221b1ecf', max_length=50),
        ),
    ]
