# Generated by Django 4.2.5 on 2023-10-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0032_alter_producto_codigo_alter_producto_codigo_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(default='37e8af63054140cdbaed1cfe2d88bd1d', max_length=50),
        ),
    ]
